# Project identification
sonar.projectKey=tdk-nurse-project-mfr
sonar.projectName=TDK Nurse Project Master Template
sonar.projectVersion=1.0.0

# Source encoding
sonar.sourceEncoding=UTF-8

# Path to sources
sonar.sources=apps,libs
sonar.tests=apps,libs
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/prisma/migrations/**,**/*.config.js,**/*.config.ts,**/public/**,**/infra/**

# Coverage reporting (à adapter selon votre outil de coverage, ex: vitest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Specific configuration for TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Multi-module mapping (Optional but recommended for SonarQube)
sonar.modules=admin-gateway,appointment-service,patient-portal,libs-shared

admin-gateway.sonar.projectBaseDir=apps/admin-gateway
appointment-service.sonar.projectBaseDir=apps/appointment-service
patient-portal.sonar.projectBaseDir=apps/patient-portal
libs-shared.sonar.projectBaseDir=libs