services:
  db:
    image: postgres:16
    container_name: appointment-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appointments_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: appointment-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: