# k8s/overlays/development/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: patches/replicas.yaml

# This section will be managed automatically by the CI
images:
- name: tdksoft341/tdk-nurse-project-mfr
  newName: tdksoft341/tdk-nurse-project-mfr
  newTag: latest

# Adding a suffix to distinguish dev resources
nameSuffix: -dev
commonLabels:
  env: development
