apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: dev-
commonLabels:
  env: development
patches:
  - path: patches/replicas.yaml
configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://api.dev.tdksoft.com