apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
# ArgoCD will specifically monitor this folder
commonLabels:
  env: production
patches:
  - path: patches/scale-and-resources.yaml
configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.tdksoft.com
images:
  - name: tdksoftconsulting/nextjs-app
    newTag: v1.0.0 # This tag will be updated by the release.yml file