apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: app
        image: tdksoftconsulting/nextjs-app:latest # Will be updated by the CI
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config