apiVersion: v1
kind: Service
metadata:
  name: mfr-care
  labels:
    app: mfr-care
    app.kubernetes.io/name: mfr-care
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: mfr-care
